const express=require("express")
const cors=require("cors")
const Connection=require("./Connection")
require("dotenv").config()
const Routes=require("./Routes/Route")
const Download=require("./Routes/Download")
const app=express()
app.use(express.json())
app.use(cors({exposedHeaders: ['Content-Disposition']}))
app.use('/uploads', express.static('uploads'));
Connection()

app.use("/api",Routes)
app.use("/download",Download)
app.listen(process.env.PORT || 3010,()=>console.log("Server Started At:"+process.env.PORT || 3010))